# Site settings
name: Aayush Pandey
# email the first letter of my first name + "x" + my surname at the domain (outlook [dot] com)

username: aayushpdy
description: "This page is created using git, jekyll, markdown, vim and other open-source software."
baseurl: ""
url: "samueljohnson.io"

# Build settings
markdown: kramdown
#permalinks: pretty
permalink: /blog/:year/:month/:day/:title/
gems:
          - jekyll-sitemap

theme: jekyll-theme-leap-day
